In [1]:
import pandas as pd
import numpy as np

In [15]:
df_educatie = pd.read_csv('input/Educatie.csv')
df_populatie = pd.read_csv('input/PopulatieJudete.csv')
df_ronuts = pd.read_csv('input/RO_NUTS.csv')

In [16]:
df_educatie

   Judet  Superior  Liceal  Gimnazial  Primar  FaraScoala  PersoaneAnalfabete
0     ab     39697   78171      79505   42171        8328                3194
1     ar     53019   90593     115844   54017        8512                3920
2     ag     77707  150472     129429   72343       11382                4368
3     bc     55431  105090     155383   88953       19306                8806
4     bh     72214  133992     131037   67461       18166                3804
5     bn     26144   48419      87274   41865        8379                3902
6     bt     25497   69747     119289   73367       14669                6281
7     br     31522   60281      88961   46437       10596                5321
8     bv     89606  135797     108744   44807       11279                3505
9      b    577122  519306     265426  114285       15006                3342
10    bz     36595   84595     121314   75274       14703                6817
11    cl     77707  150472     129429   72343       11382                4368
12    cs     29142   64632      87329   39089        6663                2688
13    cj    131030  183498     134648   62934       13879                4873
14    ct     99338  168189     160050   75405       17785                8106
15    cv     18197   45842      57219   24166        7271                4024
16    db     46022  120706     131920   72932       16587                8093
17    dj     85575  156116     146329   96202       19204                8106
18    gl     56463   99574     138346   78928       18359                8284
19    gr     17169   49526      91114   52594       12771               10161
20    gj     38875   87800      77366   40091        8238                3906
21    hr     26508   80404      81969   31871        7329                3228
22    hd     51789  100453      98492   50062        7570                3324
23    il     19137   47595      72442   47546       14339                8082
24    is    100688  145810     181176  112161       21319                9051
25    if     56539   83034      93196   46974       11317                6344
26    mm     48215  101950     144101   56287       13173                4234
27    mh     25694   60963      69441   37843        9274                4876
28    ms     57771  114689     131626   69608       16538                8498
29    nt     39443   73997     137000   72751       12078                4464
30    ot     33520   93733     107366   73479       13877                5566
31    ph     93938  170797     170140   99493       17113                7075
32    sj     24524   49388      58405   29705        7469                3669
33    sm     30589   74274     105871   34555       11438                4655
34    sb     56005   85790      90631   38917        8462                2753
35    sv     51590  106808     194971   87395       16869                5696
36    tr     24605   75139      99803   75861       15577                9226
37    tm    119213  170505     161880   61081       14397                5854
38    tl     17097   40026      59490   29981        8153                4343
39    vl     40384   87613      89019   50757       10125                3743
40    vs     24412   60103     113813   74093       14928                7467
41    vn     27333   60923      97753   58207       12969                6637

In [17]:
df_populatie

   Judet  Populatie
0     ab     381185
1     ag     646530
2     ar     474347
3      b    2107399
4     bc     747689
5     bh     619475
6     bn     329490
7     br     356380
8     bt     456404
9     bv     631356
10    bz     479018
11    cj     722438
12    cl     317592
13    cs     328297
14    ct     770220
15    cv     228852
16    db     528791
17    dj     700840
18    gj     366429
19    gl     632255
20    gr     276930
21    hd     470223
22    hr     333789
23    if     390919
24    il     293940
25    is     921056
26    mh     287005
27    mm     526197
28    ms     596352
29    nt     578007
30    ot     450333
31    ph     809394
32    sb     464513
33    sj     247702
34    sm     390939
35    sv     744854
36    tl     244392
37    tm     743427
38    tr     389670
39    vl     403311
40    vn     391586
41    vs     481272

In [18]:
df_ronuts

   IndicativJudet             NumeJudet          Regiune MacroRegiune
0              ab                  Alba           Centru          RO1
1              ag                 Arges              Sud          RO3
2              ar                  Arad             Vest          RO4
3               b  Municipiul Bucuresti  Bucuresti-Ilfov          RO3
4              bc                 Bacau         Nord-Est          RO2
5              bh                 Bihor        Nord-Vest          RO1
6              bn       Bistrita-Nasaud        Nord-Vest          RO1
7              br                Braila          Sud-Est          RO2
8              bt              Botosani         Nord-Est          RO2
9              bv                Brasov           Centru          RO1
10             bz                 Buzau          Sud-Est          RO2
11             cj                  Cluj        Nord-Vest          RO1
12             cl              Calarasi              Sud          RO3
13             cs         Caras-Severin             Vest          RO4
14             ct             Constanta          Sud-Est          RO2
15             cv               Covasna           Centru          RO1
16             db             Dambovita              Sud          RO3
17             dj                  Dolj         Sud-Vest          RO4
18             gj                  Gorj         Sud-Vest          RO4
19             gl                Galati          Sud-Est          RO2
20             gr               Giurgiu              Sud          RO3
21             hd             Hunedoara             Vest          RO4
22             hr              Harghita           Centru          RO1
23             if                 Ilfov  Bucuresti-Ilfov          RO3
24             il              Ialomita              Sud          RO3
25             is                  Iasi         Nord-Est          RO2
26             mh             Mehedinti         Sud-Vest          RO4
27             mm             Maramures        Nord-Vest          RO1
28             ms                 Mures           Centru          RO1
29             nt                 Neamt         Nord-Est          RO2
30             ot                   Olt         Sud-Vest          RO4
31             ph               Prahova              Sud          RO3
32             sb                 Sibiu           Centru          RO1
33             sj                 Salaj        Nord-Vest          RO1
34             sm             Satu Mare        Nord-Vest          RO1
35             sv               Suceava         Nord-Est          RO2
36             tl                Tulcea          Sud-Est          RO2
37             tm                 Timis             Vest          RO4
38             tr             Teleorman              Sud          RO3
39             vl                Valcea         Sud-Vest          RO4
40             vn               Vrancea          Sud-Est          RO2
41             vs                Vaslui         Nord-Est          RO2

### 1_Sa se salveze judetele in care numarul total de analfabeti este mai mare decat numarul total de persoane fara scoala

In [19]:
mask = df_educatie['PersoaneAnalfabete'] > df_educatie['FaraScoala']
df_jud_analfabete = df_educatie[mask]

In [20]:
df_jud_analfabete

Empty DataFrame
Columns: [Judet, Superior, Liceal, Gimnazial, Primar, FaraScoala, PersoaneAnalfabete]
Index: []

### 2_Sa se calculeze diferenta dintre presoane fara scoala la 1000 de locuitori si persoane analfabete la 1000 de locuitori per regiune

In [24]:
df_merge = df_educatie.merge(df_ronuts[['IndicativJudet', 'Regiune']], left_on='Judet', right_on='IndicativJudet', how='inner')
df_merge.drop('IndicativJudet', axis=1, inplace=True)

In [131]:
df_merge = df_merge.merge(df_populatie, left_on='Judet', right_on='Judet')

In [32]:
df_merge

,Judet,Superior,Liceal,Gimnazial,Primar,FaraScoala,PersoaneAnalfabete,Regiune,Populatie
0,ab,39697,78171,79505,42171,8328,3194,Centru,381185
1,ar,53019,90593,115844,54017,8512,3920,Vest,474347
2,ag,77707,150472,129429,72343,11382,4368,Sud,646530
3,bc,55431,105090,155383,88953,19306,8806,Nord-Est,747689
4,bh,72214,133992,131037,67461,18166,3804,Nord-Vest,619475
5,bn,26144,48419,87274,41865,8379,3902,Nord-Vest,329490
6,bt,25497,69747,119289,73367,14669,6281,Nord-Est,456404
7,br,31522,60281,88961,46437,10596,5321,Sud-Est,356380
8,bv,89606,135797,108744,44807,11279,3505,Centru,631356
9,b,577122,519306,265426,114285,15006,3342,Bucuresti-Ilfov,2107399
10,bz,36595,84595,121314,75274,14703,6817,Sud-Est,479018
11,cl,77707,150472,129429,72343,11382,4368,Sud,317592
12,cs,29142,64632,87329,39089,6663,2688,Vest,328297
13,cj,131030,183498,134648,62934,13879,4873,Nord-Vest,722438
14,ct,99338,168189,160050,75405,17785,8106,Sud-Est,770220
15,cv,18197,45842,57219,24166,7271,4024,Centru,228852
16,db,46022,120706,131920,72932,16587,8093,Sud,528791
17,dj,85575,156116,146329,96202,19204,8106,Sud-Vest,700840
18,gl,56463,99574,138346,78928,18359,8284,Sud-Est,632255
19,gr,17169,49526,91114,52594,12771,10161,Sud,276930
20,gj,38875,87800,77366,40091,8238,3906,Sud-Vest,366429
21,hr,26508,80404,81969,31871,7329,3228,Centru,333789
22,hd,51789,100453,98492,50062,7570,3324,Vest,470223
23,il,19137,47595,72442,47546,14339,8082,Sud,293940
24,is,100688,145810,181176,112161,21319,9051,Nord-Est,921056
25,if,56539,83034,93196,46974,11317,6344,Bucuresti-Ilfov,390919
26,mm,48215,101950,144101,56287,13173,4234,Nord-Vest,526197
27,mh,25694,60963,69441,37843,9274,4876,Sud-Vest,287005
28,ms,57771,114689,131626,69608,16538,8498,Centru,596352
29,nt,39443,73997,137000,72751,12078,4464,Nord-Est,578007
30,ot,33520,93733,107366,73479,13877,5566,Sud-Vest,450333
31,ph,93938,170797,170140,99493,17113,7075,Sud,809394
32,sj,24524,49388,58405,29705,7469,3669,Nord-Vest,247702
33,sm,30589,74274,105871,34555,11438,4655,Nord-Vest,390939
34,sb,56005,85790,90631,38917,8462,2753,Centru,464513
35,sv,51590,106808,194971,87395,16869,5696,Nord-Est,744854
36,tr,24605,75139,99803,75861,15577,9226,Sud,389670
37,tm,119213,170505,161880,61081,14397,5854,Vest,743427
38,tl,17097,40026,59490,29981,8153,4343,Sud-Est,244392
39,vl,40384,87613,89019,50757,10125,3743,Sud-Vest,403311
40,vs,24412,60103,113813,74093,14928,7467,Nord-Est,481272
41,vn,27333,60923,97753,58207,12969,6637,Sud-Est,391586

In [174]:
df_needed = pd.DataFrame()
df_needed['Regiune'] = df_merge['Regiune']
df_needed['FaraScoala'] = df_merge['FaraScoala']
df_needed['Analfabeti'] = df_merge['PersoaneAnalfabete']
df_needed['Populatie'] = df_merge['Populatie']
df_needed.set_index('Regiune')

KeyError: 'Regiune'

In [75]:
df_needed.to_csv('test')

In [106]:
def calc_indic(group:pd.DataFrame):
    print(group)
  # First sum up the values for each column within the group
    fara_scoala_sum = group['FaraScoala'].sum()
    analfabeti_sum = group['Analfabeti'].sum()
    populatie_sum = group['Populatie'].sum()
    
    # Calculate the difference of the sums
    indicator = (fara_scoala_sum*1000)/populatie_sum - (analfabeti_sum*1000)/populatie_sum
    
    # Return a single value for the group
    return indicator

In [127]:
df_fin = df_needed.groupby('Regiune').apply(calc_indic, include_groups=False)

KeyError: 'Judet'

In [108]:
df_fin.to_csv('test')

In [122]:
def get_jud_max(group:pd.DataFrame):
    print(group)
    return group.idxmax()

In [132]:
df_merge.set_index('Judet', inplace=True)

In [133]:
df_rate_maxime = df_merge.groupby('Regiune').apply(get_jud_max, include_groups=False)

KeyError: 'Regiune'

In [126]:
df_rate_maxime

,Judet,Superior,Liceal,Gimnazial,Primar,FaraScoala,PersoaneAnalfabete,Populatie
Regiune,,,,,,,,
Bucuresti-Ilfov,Bucuresti-Ilfov,Bucuresti-Ilfov,Bucuresti-Ilfov,Bucuresti-Ilfov,Bucuresti-Ilfov,Bucuresti-Ilfov,Bucuresti-Ilfov,Bucuresti-Ilfov
Centru,Centru,Centru,Centru,Centru,Centru,Centru,Centru,Centru
Nord-Est,Nord-Est,Nord-Est,Nord-Est,Nord-Est,Nord-Est,Nord-Est,Nord-Est,Nord-Est
Nord-Vest,Nord-Vest,Nord-Vest,Nord-Vest,Nord-Vest,Nord-Vest,Nord-Vest,Nord-Vest,Nord-Vest
Sud,Sud,Sud,Sud,Sud,Sud,Sud,Sud,Sud
Sud-Est,Sud-Est,Sud-Est,Sud-Est,Sud-Est,Sud-Est,Sud-Est,Sud-Est,Sud-Est
Sud-Vest,Sud-Vest,Sud-Vest,Sud-Vest,Sud-Vest,Sud-Vest,Sud-Vest,Sud-Vest,Sud-Vest
Vest,Vest,Vest,Vest,Vest,Vest,Vest,Vest,Vest

In [141]:
def get_max_jud(group:pd.DataFrame):
    return group.idxmax()

In [139]:
df_new_merge = df_educatie.merge(df_populatie, left_on='Judet', right_on='Judet', how='inner')
df_new_merge = df_new_merge.merge(df_ronuts[['IndicativJudet', 'Regiune']], left_on='Judet', right_on='IndicativJudet', how='inner').set_index('Judet')
df_new_merge.drop('IndicativJudet', axis=1, inplace=True)

In [143]:
df_new_merge.groupby('Regiune').apply(get_max_jud, include_groups=False)

,Superior,Liceal,Gimnazial,Primar,FaraScoala,PersoaneAnalfabete,Populatie
Regiune,,,,,,,
Bucuresti-Ilfov,b,b,b,b,b,if,b
Centru,bv,bv,ms,ms,ms,ms,bv
Nord-Est,is,is,sv,is,is,is,is
Nord-Vest,cj,cj,mm,bh,bh,cj,cj
Sud,ph,ph,ph,ph,ph,gr,ph
Sud-Est,ct,ct,ct,gl,gl,gl,ct
Sud-Vest,dj,dj,dj,dj,dj,dj,dj
Vest,tm,tm,tm,tm,tm,tm,tm

In [140]:
df_new_merge

,Superior,Liceal,Gimnazial,Primar,FaraScoala,PersoaneAnalfabete,Populatie,Regiune
Judet,,,,,,,,
ab,39697,78171,79505,42171,8328,3194,381185,Centru
ar,53019,90593,115844,54017,8512,3920,474347,Vest
ag,77707,150472,129429,72343,11382,4368,646530,Sud
bc,55431,105090,155383,88953,19306,8806,747689,Nord-Est
bh,72214,133992,131037,67461,18166,3804,619475,Nord-Vest
bn,26144,48419,87274,41865,8379,3902,329490,Nord-Vest
bt,25497,69747,119289,73367,14669,6281,456404,Nord-Est
br,31522,60281,88961,46437,10596,5321,356380,Sud-Est
bv,89606,135797,108744,44807,11279,3505,631356,Centru
b,577122,519306,265426,114285,15006,3342,2107399,Bucuresti-Ilfov
bz,36595,84595,121314,75274,14703,6817,479018,Sud-Est
cl,77707,150472,129429,72343,11382,4368,317592,Sud
cs,29142,64632,87329,39089,6663,2688,328297,Vest
cj,131030,183498,134648,62934,13879,4873,722438,Nord-Vest
ct,99338,168189,160050,75405,17785,8106,770220,Sud-Est
cv,18197,45842,57219,24166,7271,4024,228852,Centru
db,46022,120706,131920,72932,16587,8093,528791,Sud
dj,85575,156116,146329,96202,19204,8106,700840,Sud-Vest
gl,56463,99574,138346,78928,18359,8284,632255,Sud-Est
gr,17169,49526,91114,52594,12771,10161,276930,Sud
gj,38875,87800,77366,40091,8238,3906,366429,Sud-Vest
hr,26508,80404,81969,31871,7329,3228,333789,Centru
hd,51789,100453,98492,50062,7570,3324,470223,Vest
il,19137,47595,72442,47546,14339,8082,293940,Sud
is,100688,145810,181176,112161,21319,9051,921056,Nord-Est
if,56539,83034,93196,46974,11317,6344,390919,Bucuresti-Ilfov
mm,48215,101950,144101,56287,13173,4234,526197,Nord-Vest
mh,25694,60963,69441,37843,9274,4876,287005,Sud-Vest
ms,57771,114689,131626,69608,16538,8498,596352,Centru
nt,39443,73997,137000,72751,12078,4464,578007,Nord-Est
ot,33520,93733,107366,73479,13877,5566,450333,Sud-Vest
ph,93938,170797,170140,99493,17113,7075,809394,Sud
sj,24524,49388,58405,29705,7469,3669,247702,Nord-Vest
sm,30589,74274,105871,34555,11438,4655,390939,Nord-Vest
sb,56005,85790,90631,38917,8462,2753,464513,Centru
sv,51590,106808,194971,87395,16869,5696,744854,Nord-Est
tr,24605,75139,99803,75861,15577,9226,389670,Sud
tm,119213,170505,161880,61081,14397,5854,743427,Vest
tl,17097,40026,59490,29981,8153,4343,244392,Sud-Est
vl,40384,87613,89019,50757,10125,3743,403311,Sud-Vest
vs,24412,60103,113813,74093,14928,7467,481272,Nord-Est
vn,27333,60923,97753,58207,12969,6637,391586,Sud-Est

In [159]:
df_new_merge_indicatori = pd.DataFrame()
df_new_merge_indicatori['Superior'] = df_new_merge['Superior']*1000/df_new_merge['Populatie']
df_new_merge_indicatori['Liceal'] = df_new_merge['Liceal']*1000/df_new_merge['Populatie']
df_new_merge_indicatori['Gimnazial'] = df_new_merge['Gimnazial']*1000/df_new_merge['Populatie']
df_new_merge_indicatori['Primar'] = df_new_merge['Primar']*1000/df_new_merge['Populatie']
df_new_merge_indicatori['FaraScoala'] = df_new_merge['FaraScoala']*1000/df_new_merge['Populatie']
df_new_merge_indicatori['PersoaneAnalfabete'] = df_new_merge['PersoaneAnalfabete']*1000/df_new_merge['Populatie']
df_new_merge_indicatori['Regiune'] = df_new_merge['Regiune']

In [161]:
df_new_merge_indicatori.groupby('Regiune').apply(get_max_jud, include_groups=False)

                Superior Liceal Gimnazial Primar FaraScoala PersoaneAnalfabete
Regiune
Bucuresti-Ilfov        b      b        if     if         if                 if
Centru                bv     hr        cv     ms         cv                 cv
Nord-Est              is     is        sv     bt         bt                 vs
Nord-Vest             cj     cj        mm     bn         sj                 sj
Sud                   cl     cl        cl     cl         il                 gr
Sud-Est               ct     ct        bz     bz         tl                 tl
Sud-Vest              dj     gj        mh     ot         mh                 mh
Vest                  tm     tm        cs     cs         cs                 ar

In [168]:
def get_max_jud_fara_prelucrari(group:pd.DataFrame):
    print(group)
    for column in group.columns:
        group[column] = group[column]*1000/group['Populatie']
    print('----------TRANSFORMED------------')
    print(group)

    return group.idxmax()

In [166]:
df_new_merge_f = pd.DataFrame()
df_new_merge_f['Superior'] = df_new_merge['Superior']
df_new_merge_f['Liceal'] = df_new_merge['Liceal']
df_new_merge_f['Gimnazial'] = df_new_merge['Gimnazial']
df_new_merge_f['Primar'] = df_new_merge['Primar']
df_new_merge_f['FaraScoala'] = df_new_merge['FaraScoala']
df_new_merge_f['PersoaneAnalfabete'] = df_new_merge['PersoaneAnalfabete']
df_new_merge_f['Regiune'] = df_new_merge['Regiune']
df_new_merge_f['Populatie'] = df_new_merge['Populatie']

In [172]:
df_new_merge_f_final = df_new_merge_f.groupby('Regiune').apply(get_max_jud_fara_prelucrari, include_groups=False)
df_new_merge_f_final.drop('Populatie', axis=1, inplace=True)

       Superior  Liceal  Gimnazial  Primar  FaraScoala  PersoaneAnalfabete  \
Judet
b        577122  519306     265426  114285       15006                3342
if        56539   83034      93196   46974       11317                6344

       Populatie
Judet
b        2107399
if        390919
----------TRANSFORMED------------
         Superior      Liceal   Gimnazial      Primar  FaraScoala  \
Judet
b      273.855117  246.420350  125.949571   54.230357    7.120626
if     144.630985  212.407174  238.402329  120.163001   28.949731

       PersoaneAnalfabete  Populatie
Judet
b                1.585841     1000.0
if              16.228426     1000.0
       Superior  Liceal  Gimnazial  Primar  FaraScoala  PersoaneAnalfabete  \
Judet
ab        39697   78171      79505   42171        8328                3194
bv        89606  135797     108744   44807       11279                3505
cv        18197   45842      57219   24166        7271                4024
hr        26508   80404      81969   31871        7329                3228
ms        57771  114689     131626   69608       16538                8498
sb        56005   85790      90631   38917        8462                2753

       Populatie
Judet
ab        381185
bv        631356
cv        228852
hr        333789
ms        596352
sb        464513
----------TRANSFORMED------------
         Superior      Liceal   Gimnazial      Primar  FaraScoala  \
Judet
ab     104.141034  205.073652  208.573265  110.631321   21.847659
bv     141.926267  215.087843  172.238800   70.969469   17.864723
cv      79.514271  200.312866  250.026218  105.596630   31.771625
hr      79.415439  240.882713  245.571304   95.482475   21.956985
ms      96.873994  192.317624  220.718636  116.723009   27.731944
sb     120.567132  184.688050  195.109717   83.780217   18.216928

       PersoaneAnalfabete  Populatie
Judet
ab               8.379133     1000.0
bv               5.551543     1000.0
cv              17.583416     1000.0
hr               9.670780     1000.0
ms              14.249973     1000.0
sb               5.926637     1000.0
       Superior  Liceal  Gimnazial  Primar  FaraScoala  PersoaneAnalfabete  \
Judet
bc        55431  105090     155383   88953       19306                8806
bt        25497   69747     119289   73367       14669                6281
is       100688  145810     181176  112161       21319                9051
nt        39443   73997     137000   72751       12078                4464
sv        51590  106808     194971   87395       16869                5696
vs        24412   60103     113813   74093       14928                7467

       Populatie
Judet
bc        747689
bt        456404
is        921056
nt        578007
sv        744854
vs        481272
----------TRANSFORMED------------
         Superior      Liceal   Gimnazial      Primar  FaraScoala  \
Judet
bc      74.136439  140.553091  207.817689  118.970588   25.820896
bt      55.864979  152.818555  261.367122  160.750125   32.140384
is     109.318000  158.307421  196.704652  121.774355   23.146258
nt      68.239658  128.020941  237.021351  125.865258   20.895941
sv      69.261896  143.394544  261.757338  117.331719   22.647391
vs      50.723915  124.883642  236.483735  153.952443   31.017803

       PersoaneAnalfabete  Populatie
Judet
bc              11.777624     1000.0
bt              13.761930     1000.0
is               9.826764     1000.0
nt               7.723090     1000.0
sv               7.647136     1000.0
vs              15.515135     1000.0
       Superior  Liceal  Gimnazial  Primar  FaraScoala  PersoaneAnalfabete  \
Judet
bh        72214  133992     131037   67461       18166                3804
bn        26144   48419      87274   41865        8379                3902
cj       131030  183498     134648   62934       13879                4873
mm        48215  101950     144101   56287       13173                4234
sj        24524   49388      58405   29705        7469                3669
sm        30589   74274     105871   34555       11438                4655

       Populatie
Judet
bh        619475
bn        329490
cj        722438
mm        526197
sj        247702
sm        390939
----------TRANSFORMED------------
         Superior      Liceal   Gimnazial      Primar  FaraScoala  \
Judet
bh     116.572904  216.299286  211.529117  108.900278   29.324832
bn      79.346869  146.951349  264.876021  127.060002   25.430210
cj     181.371965  253.998267  186.380008   87.113358   19.211337
mm      91.629181  193.748729  273.853709  106.969443   25.034350
sj      99.006064  199.384745  235.787357  119.922326   30.153168
sm      78.244944  189.988719  270.812070   88.389749   29.257761

       PersoaneAnalfabete  Populatie
Judet
bh               6.140684     1000.0
bn              11.842545     1000.0
cj               6.745216     1000.0
mm               8.046416     1000.0
sj              14.812153     1000.0
sm              11.907228     1000.0
       Superior  Liceal  Gimnazial  Primar  FaraScoala  PersoaneAnalfabete  \
Judet
ag        77707  150472     129429   72343       11382                4368
cl        77707  150472     129429   72343       11382                4368
db        46022  120706     131920   72932       16587                8093
gr        17169   49526      91114   52594       12771               10161
il        19137   47595      72442   47546       14339                8082
ph        93938  170797     170140   99493       17113                7075
tr        24605   75139      99803   75861       15577                9226

       Populatie
Judet
ag        646530
cl        317592
db        528791
gr        276930
il        293940
ph        809394
tr        389670
----------TRANSFORMED------------
         Superior      Liceal   Gimnazial      Primar  FaraScoala  \
Judet
ag     120.190865  232.737847  200.190246  111.894266   17.604752
cl     244.675559  473.790272  407.532306  227.785964   35.838434
db      87.032495  228.267879  249.474745  137.922166   31.367780
gr      61.997617  178.839418  329.014552  189.918030   46.116347
il      65.105123  161.920800  246.451657  161.754099   48.782064
ph     116.059669  211.018367  210.206648  122.922829   21.142979
tr      63.143172  192.827264  256.121847  194.680114   39.974851

       PersoaneAnalfabete  Populatie
Judet
ag               6.756067     1000.0
cl              13.753495     1000.0
db              15.304723     1000.0
gr              36.691583     1000.0
il              27.495407     1000.0
ph               8.741108     1000.0
tr              23.676444     1000.0
       Superior  Liceal  Gimnazial  Primar  FaraScoala  PersoaneAnalfabete  \
Judet
br        31522   60281      88961   46437       10596                5321
bz        36595   84595     121314   75274       14703                6817
ct        99338  168189     160050   75405       17785                8106
gl        56463   99574     138346   78928       18359                8284
tl        17097   40026      59490   29981        8153                4343
vn        27333   60923      97753   58207       12969                6637

       Populatie
Judet
br        356380
bz        479018
ct        770220
gl        632255
tl        244392
vn        391586
----------TRANSFORMED------------
         Superior      Liceal   Gimnazial      Primar  FaraScoala  \
Judet
br      88.450530  169.148100  249.623997  130.301925   29.732308
bz      76.395877  176.600879  253.255619  157.142320   30.694045
ct     128.973540  218.364883  207.797772   97.900600   23.090805
gl      89.304157  157.490253  218.813612  124.835707   29.037335
tl      69.957282  163.777865  243.420407  122.675865   33.360339
vn      69.800759  155.580128  249.633542  148.644231   33.119162

       PersoaneAnalfabete  Populatie
Judet
br              14.930692     1000.0
bz              14.231198     1000.0
ct              10.524266     1000.0
gl              13.102308     1000.0
tl              17.770631     1000.0
vn              16.949023     1000.0
       Superior  Liceal  Gimnazial  Primar  FaraScoala  PersoaneAnalfabete  \
Judet
dj        85575  156116     146329   96202       19204                8106
gj        38875   87800      77366   40091        8238                3906
mh        25694   60963      69441   37843        9274                4876
ot        33520   93733     107366   73479       13877                5566
vl        40384   87613      89019   50757       10125                3743

       Populatie
Judet
dj        700840
gj        366429
mh        287005
ot        450333
vl        403311
----------TRANSFORMED------------
         Superior      Liceal   Gimnazial      Primar  FaraScoala  \
Judet
dj     122.103476  222.755550  208.790880  137.266709   27.401404
gj     106.091494  239.609856  211.135036  109.410008   22.481845
mh      89.524573  212.410934  241.950489  131.854846   32.313026
ot      74.433808  208.141531  238.414684  163.165924   30.814975
vl     100.131164  217.234343  220.720486  125.850770   25.104696

       PersoaneAnalfabete  Populatie
Judet
dj              11.566121     1000.0
gj              10.659637     1000.0
mh              16.989251     1000.0
ot              12.359743     1000.0
vl               9.280679     1000.0
       Superior  Liceal  Gimnazial  Primar  FaraScoala  PersoaneAnalfabete  \
Judet
ar        53019   90593     115844   54017        8512                3920
cs        29142   64632      87329   39089        6663                2688
hd        51789  100453      98492   50062        7570                3324
tm       119213  170505     161880   61081       14397                5854

       Populatie
Judet
ar        474347
cs        328297
hd        470223
tm        743427
----------TRANSFORMED------------
         Superior      Liceal   Gimnazial      Primar  FaraScoala  \
Judet
ar     111.772605  190.984659  244.217841  113.876550   17.944669
cs      88.767183  196.870517  266.006086  119.065968   20.295647
hd     110.137105  213.628427  209.458066  106.464380   16.098745
tm     160.356027  229.350024  217.748347   82.161396   19.365721

       PersoaneAnalfabete  Populatie
Judet
ar               8.263992     1000.0
cs               8.187708     1000.0
hd               7.068986     1000.0
tm               7.874344     1000.0

In [173]:
df_new_merge_f_final

                Superior Liceal Gimnazial Primar FaraScoala PersoaneAnalfabete
Regiune
Bucuresti-Ilfov        b      b        if     if         if                 if
Centru                bv     hr        cv     ms         cv                 cv
Nord-Est              is     is        sv     bt         bt                 vs
Nord-Vest             cj     cj        mm     bn         sj                 sj
Sud                   cl     cl        cl     cl         il                 gr
Sud-Est               ct     ct        bz     bz         tl                 tl
Sud-Vest              dj     gj        mh     ot         mh                 mh
Vest                  tm     tm        cs     cs         cs                 ar